/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const I18nText = IDL.Record({
  'ar' : IDL.Text,
  'en' : IDL.Text,
  'ta' : IDL.Text,
});
export const MenuCategory = IDL.Variant({
  'other' : IDL.Null,
  'rice' : IDL.Null,
  'sides' : IDL.Null,
  'sweets' : IDL.Null,
  'biryani' : IDL.Null,
});
export const NewMenuItemInput = IDL.Record({
  'name' : I18nText,
  'isAvailable' : IDL.Bool,
  'description' : I18nText,
  'imageUrl' : IDL.Text,
  'category' : MenuCategory,
  'price' : IDL.Opt(IDL.Nat),
});
export const MenuItemId = IDL.Nat;
export const MenuItem = IDL.Record({
  'id' : MenuItemId,
  'name' : I18nText,
  'isAvailable' : IDL.Bool,
  'description' : I18nText,
  'imageUrl' : IDL.Text,
  'category' : MenuCategory,
  'price' : IDL.Opt(IDL.Nat),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const OrderStatus = IDL.Variant({
  'placed' : IDL.Null,
  'beingPrepared' : IDL.Null,
  'delivered' : IDL.Null,
  'ready' : IDL.Null,
});
export const PaymentMethod = IDL.Variant({ 'qr' : IDL.Null, 'cod' : IDL.Null });
export const Timestamp = IDL.Int;
export const OrderId = IDL.Nat;
export const OrderItem = IDL.Record({
  'name' : IDL.Text,
  'quantity' : IDL.Nat,
  'unitPrice' : IDL.Nat,
  'menuItemId' : MenuItemId,
});
export const Order = IDL.Record({
  'customerName' : IDL.Text,
  'status' : OrderStatus,
  'paymentMethod' : PaymentMethod,
  'createdAt' : Timestamp,
  'orderId' : OrderId,
  'notes' : IDL.Text,
  'contactNumber' : IDL.Text,
  'items' : IDL.Vec(OrderItem),
  'totalPrice' : IDL.Nat,
});
export const PlaceOrderInput = IDL.Record({
  'customerName' : IDL.Text,
  'paymentMethod' : PaymentMethod,
  'notes' : IDL.Text,
  'contactNumber' : IDL.Text,
  'items' : IDL.Vec(
    IDL.Record({ 'quantity' : IDL.Nat, 'menuItemId' : MenuItemId })
  ),
});

export const idlService = IDL.Service({
  '_initializeAccessControl' : IDL.Func([], [], []),
  'addMenuItem' : IDL.Func([NewMenuItemInput], [MenuItem], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'getAllOrders' : IDL.Func([], [IDL.Vec(Order)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getMenuItem' : IDL.Func([MenuItemId], [IDL.Opt(MenuItem)], ['query']),
  'getMenuItems' : IDL.Func([], [IDL.Vec(MenuItem)], ['query']),
  'getOrderStatus' : IDL.Func([OrderId], [IDL.Opt(OrderStatus)], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'placeOrder' : IDL.Func([PlaceOrderInput], [Order], []),
  'removeMenuItem' : IDL.Func([MenuItemId], [IDL.Bool], []),
  'updateMenuItem' : IDL.Func(
      [MenuItemId, NewMenuItemInput],
      [IDL.Opt(MenuItem)],
      [],
    ),
  'updateOrderStatus' : IDL.Func([OrderId, OrderStatus], [IDL.Opt(Order)], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const I18nText = IDL.Record({
    'ar' : IDL.Text,
    'en' : IDL.Text,
    'ta' : IDL.Text,
  });
  const MenuCategory = IDL.Variant({
    'other' : IDL.Null,
    'rice' : IDL.Null,
    'sides' : IDL.Null,
    'sweets' : IDL.Null,
    'biryani' : IDL.Null,
  });
  const NewMenuItemInput = IDL.Record({
    'name' : I18nText,
    'isAvailable' : IDL.Bool,
    'description' : I18nText,
    'imageUrl' : IDL.Text,
    'category' : MenuCategory,
    'price' : IDL.Opt(IDL.Nat),
  });
  const MenuItemId = IDL.Nat;
  const MenuItem = IDL.Record({
    'id' : MenuItemId,
    'name' : I18nText,
    'isAvailable' : IDL.Bool,
    'description' : I18nText,
    'imageUrl' : IDL.Text,
    'category' : MenuCategory,
    'price' : IDL.Opt(IDL.Nat),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const OrderStatus = IDL.Variant({
    'placed' : IDL.Null,
    'beingPrepared' : IDL.Null,
    'delivered' : IDL.Null,
    'ready' : IDL.Null,
  });
  const PaymentMethod = IDL.Variant({ 'qr' : IDL.Null, 'cod' : IDL.Null });
  const Timestamp = IDL.Int;
  const OrderId = IDL.Nat;
  const OrderItem = IDL.Record({
    'name' : IDL.Text,
    'quantity' : IDL.Nat,
    'unitPrice' : IDL.Nat,
    'menuItemId' : MenuItemId,
  });
  const Order = IDL.Record({
    'customerName' : IDL.Text,
    'status' : OrderStatus,
    'paymentMethod' : PaymentMethod,
    'createdAt' : Timestamp,
    'orderId' : OrderId,
    'notes' : IDL.Text,
    'contactNumber' : IDL.Text,
    'items' : IDL.Vec(OrderItem),
    'totalPrice' : IDL.Nat,
  });
  const PlaceOrderInput = IDL.Record({
    'customerName' : IDL.Text,
    'paymentMethod' : PaymentMethod,
    'notes' : IDL.Text,
    'contactNumber' : IDL.Text,
    'items' : IDL.Vec(
      IDL.Record({ 'quantity' : IDL.Nat, 'menuItemId' : MenuItemId })
    ),
  });
  
  return IDL.Service({
    '_initializeAccessControl' : IDL.Func([], [], []),
    'addMenuItem' : IDL.Func([NewMenuItemInput], [MenuItem], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'getAllOrders' : IDL.Func([], [IDL.Vec(Order)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getMenuItem' : IDL.Func([MenuItemId], [IDL.Opt(MenuItem)], ['query']),
    'getMenuItems' : IDL.Func([], [IDL.Vec(MenuItem)], ['query']),
    'getOrderStatus' : IDL.Func([OrderId], [IDL.Opt(OrderStatus)], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'placeOrder' : IDL.Func([PlaceOrderInput], [Order], []),
    'removeMenuItem' : IDL.Func([MenuItemId], [IDL.Bool], []),
    'updateMenuItem' : IDL.Func(
        [MenuItemId, NewMenuItemInput],
        [IDL.Opt(MenuItem)],
        [],
      ),
    'updateOrderStatus' : IDL.Func(
        [OrderId, OrderStatus],
        [IDL.Opt(Order)],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };