/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface I18nText { 'ar' : string, 'en' : string, 'ta' : string }
export type MenuCategory = { 'other' : null } |
  { 'rice' : null } |
  { 'sides' : null } |
  { 'sweets' : null } |
  { 'biryani' : null };
export interface MenuItem {
  'id' : MenuItemId,
  'name' : I18nText,
  'isAvailable' : boolean,
  'description' : I18nText,
  'imageUrl' : string,
  'category' : MenuCategory,
  'price' : [] | [bigint],
}
export type MenuItemId = bigint;
export interface NewMenuItemInput {
  'name' : I18nText,
  'isAvailable' : boolean,
  'description' : I18nText,
  'imageUrl' : string,
  'category' : MenuCategory,
  'price' : [] | [bigint],
}
export interface Order {
  'customerName' : string,
  'status' : OrderStatus,
  'paymentMethod' : PaymentMethod,
  'createdAt' : Timestamp,
  'orderId' : OrderId,
  'notes' : string,
  'contactNumber' : string,
  'items' : Array<OrderItem>,
  'totalPrice' : bigint,
}
export type OrderId = bigint;
export interface OrderItem {
  'name' : string,
  'quantity' : bigint,
  'unitPrice' : bigint,
  'menuItemId' : MenuItemId,
}
export type OrderStatus = { 'placed' : null } |
  { 'beingPrepared' : null } |
  { 'delivered' : null } |
  { 'ready' : null };
export type PaymentMethod = { 'qr' : null } |
  { 'cod' : null };
export interface PlaceOrderInput {
  'customerName' : string,
  'paymentMethod' : PaymentMethod,
  'notes' : string,
  'contactNumber' : string,
  'items' : Array<{ 'quantity' : bigint, 'menuItemId' : MenuItemId }>,
}
export type Timestamp = bigint;
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControl' : ActorMethod<[], undefined>,
  'addMenuItem' : ActorMethod<[NewMenuItemInput], MenuItem>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'getAllOrders' : ActorMethod<[], Array<Order>>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getMenuItem' : ActorMethod<[MenuItemId], [] | [MenuItem]>,
  'getMenuItems' : ActorMethod<[], Array<MenuItem>>,
  'getOrderStatus' : ActorMethod<[OrderId], [] | [OrderStatus]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'placeOrder' : ActorMethod<[PlaceOrderInput], Order>,
  'removeMenuItem' : ActorMethod<[MenuItemId], boolean>,
  'updateMenuItem' : ActorMethod<
    [MenuItemId, NewMenuItemInput],
    [] | [MenuItem]
  >,
  'updateOrderStatus' : ActorMethod<[OrderId, OrderStatus], [] | [Order]>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];