/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface MenuItem {
    id: MenuItemId;
    name: I18nText;
    isAvailable: boolean;
    description: I18nText;
    imageUrl: string;
    category: MenuCategory;
    price?: bigint;
}
export type Timestamp = bigint;
export type MenuItemId = bigint;
export interface PlaceOrderInput {
    customerName: string;
    paymentMethod: PaymentMethod;
    notes: string;
    contactNumber: string;
    items: Array<{
        quantity: bigint;
        menuItemId: MenuItemId;
    }>;
}
export interface OrderItem {
    name: string;
    quantity: bigint;
    unitPrice: bigint;
    menuItemId: MenuItemId;
}
export interface NewMenuItemInput {
    name: I18nText;
    isAvailable: boolean;
    description: I18nText;
    imageUrl: string;
    category: MenuCategory;
    price?: bigint;
}
export interface Order {
    customerName: string;
    status: OrderStatus;
    paymentMethod: PaymentMethod;
    createdAt: Timestamp;
    orderId: OrderId;
    notes: string;
    contactNumber: string;
    items: Array<OrderItem>;
    totalPrice: bigint;
}
export type OrderId = bigint;
export interface I18nText {
    ar: string;
    en: string;
    ta: string;
}
export enum MenuCategory {
    other = "other",
    rice = "rice",
    sides = "sides",
    sweets = "sweets",
    biryani = "biryani"
}
export enum OrderStatus {
    placed = "placed",
    beingPrepared = "beingPrepared",
    delivered = "delivered",
    ready = "ready"
}
export enum PaymentMethod {
    qr = "qr",
    cod = "cod"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _initializeAccessControl(): Promise<void>;
    addMenuItem(input: NewMenuItemInput): Promise<MenuItem>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    getAllOrders(): Promise<Array<Order>>;
    getCallerUserRole(): Promise<UserRole>;
    getMenuItem(id: MenuItemId): Promise<MenuItem | null>;
    getMenuItems(): Promise<Array<MenuItem>>;
    getOrderStatus(orderId: OrderId): Promise<OrderStatus | null>;
    isCallerAdmin(): Promise<boolean>;
    placeOrder(input: PlaceOrderInput): Promise<Order>;
    removeMenuItem(id: MenuItemId): Promise<boolean>;
    updateMenuItem(id: MenuItemId, input: NewMenuItemInput): Promise<MenuItem | null>;
    updateOrderStatus(orderId: OrderId, status: OrderStatus): Promise<Order | null>;
}
import type { I18nText as _I18nText, MenuCategory as _MenuCategory, MenuItem as _MenuItem, MenuItemId as _MenuItemId, NewMenuItemInput as _NewMenuItemInput, Order as _Order, OrderId as _OrderId, OrderItem as _OrderItem, OrderStatus as _OrderStatus, PaymentMethod as _PaymentMethod, PlaceOrderInput as _PlaceOrderInput, Timestamp as _Timestamp, UserRole as _UserRole } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initializeAccessControl(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControl();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControl();
            return result;
        }
    }
    async addMenuItem(arg0: NewMenuItemInput): Promise<MenuItem> {
        if (this.processError) {
            try {
                const result = await this.actor.addMenuItem(to_candid_NewMenuItemInput_n1(this._uploadFile, this._downloadFile, arg0));
                return from_candid_MenuItem_n5(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addMenuItem(to_candid_NewMenuItemInput_n1(this._uploadFile, this._downloadFile, arg0));
            return from_candid_MenuItem_n5(this._uploadFile, this._downloadFile, result);
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n10(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n10(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async getAllOrders(): Promise<Array<Order>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllOrders();
                return from_candid_vec_n12(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllOrders();
            return from_candid_vec_n12(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n19(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n19(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMenuItem(arg0: MenuItemId): Promise<MenuItem | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getMenuItem(arg0);
                return from_candid_opt_n21(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMenuItem(arg0);
            return from_candid_opt_n21(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMenuItems(): Promise<Array<MenuItem>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMenuItems();
                return from_candid_vec_n22(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMenuItems();
            return from_candid_vec_n22(this._uploadFile, this._downloadFile, result);
        }
    }
    async getOrderStatus(arg0: OrderId): Promise<OrderStatus | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getOrderStatus(arg0);
                return from_candid_opt_n23(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getOrderStatus(arg0);
            return from_candid_opt_n23(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async placeOrder(arg0: PlaceOrderInput): Promise<Order> {
        if (this.processError) {
            try {
                const result = await this.actor.placeOrder(to_candid_PlaceOrderInput_n24(this._uploadFile, this._downloadFile, arg0));
                return from_candid_Order_n13(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.placeOrder(to_candid_PlaceOrderInput_n24(this._uploadFile, this._downloadFile, arg0));
            return from_candid_Order_n13(this._uploadFile, this._downloadFile, result);
        }
    }
    async removeMenuItem(arg0: MenuItemId): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.removeMenuItem(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.removeMenuItem(arg0);
            return result;
        }
    }
    async updateMenuItem(arg0: MenuItemId, arg1: NewMenuItemInput): Promise<MenuItem | null> {
        if (this.processError) {
            try {
                const result = await this.actor.updateMenuItem(arg0, to_candid_NewMenuItemInput_n1(this._uploadFile, this._downloadFile, arg1));
                return from_candid_opt_n21(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateMenuItem(arg0, to_candid_NewMenuItemInput_n1(this._uploadFile, this._downloadFile, arg1));
            return from_candid_opt_n21(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateOrderStatus(arg0: OrderId, arg1: OrderStatus): Promise<Order | null> {
        if (this.processError) {
            try {
                const result = await this.actor.updateOrderStatus(arg0, to_candid_OrderStatus_n28(this._uploadFile, this._downloadFile, arg1));
                return from_candid_opt_n30(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateOrderStatus(arg0, to_candid_OrderStatus_n28(this._uploadFile, this._downloadFile, arg1));
            return from_candid_opt_n30(this._uploadFile, this._downloadFile, result);
        }
    }
}
function from_candid_MenuCategory_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _MenuCategory): MenuCategory {
    return from_candid_variant_n8(_uploadFile, _downloadFile, value);
}
function from_candid_MenuItem_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _MenuItem): MenuItem {
    return from_candid_record_n6(_uploadFile, _downloadFile, value);
}
function from_candid_OrderStatus_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _OrderStatus): OrderStatus {
    return from_candid_variant_n16(_uploadFile, _downloadFile, value);
}
function from_candid_Order_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Order): Order {
    return from_candid_record_n14(_uploadFile, _downloadFile, value);
}
function from_candid_PaymentMethod_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PaymentMethod): PaymentMethod {
    return from_candid_variant_n18(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n20(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_MenuItem]): MenuItem | null {
    return value.length === 0 ? null : from_candid_MenuItem_n5(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_OrderStatus]): OrderStatus | null {
    return value.length === 0 ? null : from_candid_OrderStatus_n15(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Order]): Order | null {
    return value.length === 0 ? null : from_candid_Order_n13(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    customerName: string;
    status: _OrderStatus;
    paymentMethod: _PaymentMethod;
    createdAt: _Timestamp;
    orderId: _OrderId;
    notes: string;
    contactNumber: string;
    items: Array<_OrderItem>;
    totalPrice: bigint;
}): {
    customerName: string;
    status: OrderStatus;
    paymentMethod: PaymentMethod;
    createdAt: Timestamp;
    orderId: OrderId;
    notes: string;
    contactNumber: string;
    items: Array<OrderItem>;
    totalPrice: bigint;
} {
    return {
        customerName: value.customerName,
        status: from_candid_OrderStatus_n15(_uploadFile, _downloadFile, value.status),
        paymentMethod: from_candid_PaymentMethod_n17(_uploadFile, _downloadFile, value.paymentMethod),
        createdAt: value.createdAt,
        orderId: value.orderId,
        notes: value.notes,
        contactNumber: value.contactNumber,
        items: value.items,
        totalPrice: value.totalPrice
    };
}
function from_candid_record_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _MenuItemId;
    name: _I18nText;
    isAvailable: boolean;
    description: _I18nText;
    imageUrl: string;
    category: _MenuCategory;
    price: [] | [bigint];
}): {
    id: MenuItemId;
    name: I18nText;
    isAvailable: boolean;
    description: I18nText;
    imageUrl: string;
    category: MenuCategory;
    price?: bigint;
} {
    return {
        id: value.id,
        name: value.name,
        isAvailable: value.isAvailable,
        description: value.description,
        imageUrl: value.imageUrl,
        category: from_candid_MenuCategory_n7(_uploadFile, _downloadFile, value.category),
        price: record_opt_to_undefined(from_candid_opt_n9(_uploadFile, _downloadFile, value.price))
    };
}
function from_candid_variant_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    placed: null;
} | {
    beingPrepared: null;
} | {
    delivered: null;
} | {
    ready: null;
}): OrderStatus {
    return "placed" in value ? OrderStatus.placed : "beingPrepared" in value ? OrderStatus.beingPrepared : "delivered" in value ? OrderStatus.delivered : "ready" in value ? OrderStatus.ready : value;
}
function from_candid_variant_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    qr: null;
} | {
    cod: null;
}): PaymentMethod {
    return "qr" in value ? PaymentMethod.qr : "cod" in value ? PaymentMethod.cod : value;
}
function from_candid_variant_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_variant_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    other: null;
} | {
    rice: null;
} | {
    sides: null;
} | {
    sweets: null;
} | {
    biryani: null;
}): MenuCategory {
    return "other" in value ? MenuCategory.other : "rice" in value ? MenuCategory.rice : "sides" in value ? MenuCategory.sides : "sweets" in value ? MenuCategory.sweets : "biryani" in value ? MenuCategory.biryani : value;
}
function from_candid_vec_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Order>): Array<Order> {
    return value.map((x)=>from_candid_Order_n13(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_MenuItem>): Array<MenuItem> {
    return value.map((x)=>from_candid_MenuItem_n5(_uploadFile, _downloadFile, x));
}
function to_candid_MenuCategory_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: MenuCategory): _MenuCategory {
    return to_candid_variant_n4(_uploadFile, _downloadFile, value);
}
function to_candid_NewMenuItemInput_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: NewMenuItemInput): _NewMenuItemInput {
    return to_candid_record_n2(_uploadFile, _downloadFile, value);
}
function to_candid_OrderStatus_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: OrderStatus): _OrderStatus {
    return to_candid_variant_n29(_uploadFile, _downloadFile, value);
}
function to_candid_PaymentMethod_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PaymentMethod): _PaymentMethod {
    return to_candid_variant_n27(_uploadFile, _downloadFile, value);
}
function to_candid_PlaceOrderInput_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PlaceOrderInput): _PlaceOrderInput {
    return to_candid_record_n25(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n11(_uploadFile, _downloadFile, value);
}
function to_candid_record_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    name: I18nText;
    isAvailable: boolean;
    description: I18nText;
    imageUrl: string;
    category: MenuCategory;
    price?: bigint;
}): {
    name: _I18nText;
    isAvailable: boolean;
    description: _I18nText;
    imageUrl: string;
    category: _MenuCategory;
    price: [] | [bigint];
} {
    return {
        name: value.name,
        isAvailable: value.isAvailable,
        description: value.description,
        imageUrl: value.imageUrl,
        category: to_candid_MenuCategory_n3(_uploadFile, _downloadFile, value.category),
        price: value.price ? candid_some(value.price) : candid_none()
    };
}
function to_candid_record_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    customerName: string;
    paymentMethod: PaymentMethod;
    notes: string;
    contactNumber: string;
    items: Array<{
        quantity: bigint;
        menuItemId: MenuItemId;
    }>;
}): {
    customerName: string;
    paymentMethod: _PaymentMethod;
    notes: string;
    contactNumber: string;
    items: Array<{
        quantity: bigint;
        menuItemId: _MenuItemId;
    }>;
} {
    return {
        customerName: value.customerName,
        paymentMethod: to_candid_PaymentMethod_n26(_uploadFile, _downloadFile, value.paymentMethod),
        notes: value.notes,
        contactNumber: value.contactNumber,
        items: value.items
    };
}
function to_candid_variant_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
function to_candid_variant_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PaymentMethod): {
    qr: null;
} | {
    cod: null;
} {
    return value == PaymentMethod.qr ? {
        qr: null
    } : value == PaymentMethod.cod ? {
        cod: null
    } : value;
}
function to_candid_variant_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: OrderStatus): {
    placed: null;
} | {
    beingPrepared: null;
} | {
    delivered: null;
} | {
    ready: null;
} {
    return value == OrderStatus.placed ? {
        placed: null
    } : value == OrderStatus.beingPrepared ? {
        beingPrepared: null
    } : value == OrderStatus.delivered ? {
        delivered: null
    } : value == OrderStatus.ready ? {
        ready: null
    } : value;
}
function to_candid_variant_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: MenuCategory): {
    other: null;
} | {
    rice: null;
} | {
    sides: null;
} | {
    sweets: null;
} | {
    biryani: null;
} {
    return value == MenuCategory.other ? {
        other: null
    } : value == MenuCategory.rice ? {
        rice: null
    } : value == MenuCategory.sides ? {
        sides: null
    } : value == MenuCategory.sweets ? {
        sweets: null
    } : value == MenuCategory.biryani ? {
        biryani: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
